### ISSUE TITLE
module 'torch.optim' has no attribute 'Prodigy'

### ISSUE THREAD

**Issue by DarkAlchy** [konstmish/prodigy#2]
module 'torch.optim' has no attribute 'Prodigy'

I am on pytorch 2.

**Comment by konstmish** [comment]
I see the issue is already closed, but I'll respond just in case. The optimizer is indeed not provided as part of PyTorch, you can only import it if you install the package separately. You can do it with pip by running `pip install prodigyopt` and then the optimizer needs to be imported not from `torch.optim` but from the installed package: `from prodigyopt import Prodigy
`

**Comment by DarkAlchy** [comment]
Yes, I found that out.  Thank you.

**Comment by jj-a-li** [comment]
> 
how to imported from the  installed package？

**Comment by konstmish** [comment]
Just run `from prodigyopt import Prodigy` and then `opt = Prodigy(net.parameters())` will give you the default version of the optimizer (change `net` to the name of your initialized network if it's different).
